name: CI

on:
  push:
    branches:
      - main
    
jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Build docker image
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg SHADOW_DATABASE_URL=${{ secrets.SHADOW_DATABASE_URL }} \
            --build-arg DIRECT_URL=${{ secrets.DIRECT_URL }} \
            -t killercf/bookwise:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into container register
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Push image to container register
        run: |
          docker push killercf/bookwise:${{ steps.generate_sha.outputs.sha }}
          docker tag killercf/bookwise:${{ steps.generate_sha.outputs.sha }} killercf/bookwise:latest
          docker push killercf/bookwise:latest
